build(fix): post release hook

diff --git a/bin/release/postrelease b/bin/release/postrelease
--- a/bin/release/postrelease
+++ b/bin/release/postrelease
@@ -1,8 +1,65 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-# declare path to this script
-SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 || exit ; pwd -P )"
+REQUIRED_TOOLS=(
+  git
+  sed
+  node
+)
 
-# send all tags to remote
-git push --follow-tags origin main
-git push --tags
+# check if all requirements are met
+for TOOL in "${REQUIRED_TOOLS[@]}"; do
+  if ! command -v "${TOOL}" >/dev/null; then
+    echo "${TOOL} is required... "
+    exit 1
+  fi
+done
+
+VERSION=$(node -pe 'require("./package.json")["version"]')
+
+FILE=.env
+if [ -f "$FILE" ]; then
+  echo "exporting .env"
+  set -a # export all variables created next
+  # this routine ranges through a folder of files that we don't explicitly know (@davidsneighbour)
+  # see https://github.com/koalaman/shellcheck/wiki/SC1090
+  # shellcheck source=/dev/null
+  source "${FILE}"
+  set +a # stop exporting
+fi
+
+# update version in citation configuration
+FILE=CITATION.cff
+if test -f "$FILE"; then
+  sed -i "s/^version: .*/version: ${VERSION}/" $FILE
+  DATE=$(date +%F)
+  sed -i "s/^date-released: .*/date-released: ${DATE}/" $FILE
+  git add $FILE
+fi
+
+# add re-versioned files to recent edit
+git add data/dnb/
+git commit --amend --no-edit --quiet --signoff --no-verify
+
+# push everything up
+git push --follow-tags origin main --quiet --force
+git push --tags --quiet --force
+
+# create a release on GitHub
+GITHUB_REPO=https://github.com/${GITHUB_REPOSLUG}
+URL="$GITHUB_REPO"/"releases/edit/v""$VERSION"
+curl \
+  -X POST \
+  -H "Accept: application/vnd.github+json" \
+  -H "Authorization: token ${GITHUB_SECRET}" \
+  https://api.github.com/repos/"${GITHUB_REPOSLUG}"/releases \
+  -d "{\"tag_name\":\"v${VERSION}\",\"name\":\"v${VERSION}\",\"draft\":false,\"prerelease\":false,\"generate_release_notes\":true}"
+//xdg-open "${URL}" &>>/dev/null
+
+# get the release info into the static directory
+AUTH="-u ${GITHUB_USER}:${GITHUB_SECRET}"
+URL="https://api.github.com/repos/${GITHUB_REPOSLUG}/releases/latest"
+curl "${URL}" "${AUTH}" --output ./assets/data/build.json
+
+git add assets/data/build.json
+git commit -m "chore: add build information" --signoff --no-verify
+git push origin main --quiet
